import SwiftUI

// MARK: - Auth Gate (Serverless key-based identity)
//
// Messenger pivot: there is NO server account. The device's Ed25519 keypair
// (DeviceIdentityService) IS the identity. The only "registration" step is
// choosing a local display name. Flow: splash → onboarding → display name →
// main. The legacy email/password, OAuth, OTP and phone screens were removed.
struct AuthGateView: View {
    @State private var authService = AuthService.shared
    @AppStorage("hasSeenOnboarding") private var hasSeenOnboarding: Bool = false

    var body: some View {
        Group {
            // Priority 0: splash while the local identity loads from Keychain.
            if authService.bootState == .checking {
                LaunchView()
            }
            // Priority 1: first-run onboarding (once ever).
            else if !hasSeenOnboarding {
                OnboardingView {
                    withAnimation(.spring(response: 0.5)) {
                        hasSeenOnboarding = true
                    }
                }
            }
            // Priority 2: the ONLY registration step — pick a display name.
            else if !authService.hasChosenLocalDisplayName {
                NavigationStack {
                    DisplayNameSetupView()
                }
            }
            // Priority 3: in. The on-device keypair is the identity.
            else {
                #if targetEnvironment(macCatalyst)
                RavenMacShell()
                #else
                MainShellView()
                #endif
            }
        }
        .onAppear {
            Task {
                if authService.bootState == .checking {
                    await authService.checkExistingSession()
                }
            }
        }
    }
}

// MARK: - Display Name Setup (serverless registration)
/// The entire "sign up" flow: choose a display name. The identity is the
/// device keypair generated by DeviceIdentityService — no server, no email,
/// no password, no phone.
struct DisplayNameSetupView: View {
    @State private var authService = AuthService.shared
    @State private var name: String = ""
    @State private var isSubmitting = false
    @State private var errorText: String?
    @FocusState private var focused: Bool

    private var trimmed: String {
        name.trimmingCharacters(in: .whitespacesAndNewlines)
    }

    var body: some View {
        VStack(spacing: 28) {
            Spacer()

            Image("RavenLogo")
                .resizable()
                .scaledToFit()
                .frame(width: 84, height: 84)
                .clipShape(RoundedRectangle(cornerRadius: 18, style: .continuous))

            VStack(spacing: 8) {
                Text("Choose a display name")
                    .font(.title2.weight(.bold))

                Text("This is how people see you. No account, no email, no phone — your identity is a key that lives only on this device.")
                    .font(.subheadline)
                    .foregroundStyle(.secondary)
                    .multilineTextAlignment(.center)
                    .padding(.horizontal, 24)
            }

            LiquidGlassTextField(icon: "person", placeholder: "Display name", text: $name)
                .focused($focused)
                .submitLabel(.done)
                .onSubmit(submit)
                .padding(.horizontal, 24)

            Button(action: submit) {
                HStack(spacing: 8) {
                    if isSubmitting { ProgressView().tint(.white) }
                    Text(isSubmitting ? "Creating identity…" : "Continue")
                        .font(.headline)
                }
                .frame(maxWidth: .infinity)
                .padding()
                .background(
                    trimmed.isEmpty
                        ? AnyShapeStyle(Color.gray.opacity(0.4))
                        : AnyShapeStyle(Color.accentColor)
                )
                .foregroundStyle(.white)
                .clipShape(RoundedRectangle(cornerRadius: 14, style: .continuous))
            }
            .disabled(trimmed.isEmpty || isSubmitting)
            .padding(.horizontal, 24)

            if let errorText {
                Text(errorText)
                    .font(.footnote)
                    .foregroundStyle(.red)
                    .multilineTextAlignment(.center)
                    .padding(.horizontal, 24)
                    .transition(.opacity)
            }

            Spacer()
        }
        .navigationBarHidden(true)
        .onAppear { focused = true }
    }

    private func submit() {
        guard !trimmed.isEmpty, !isSubmitting else { return }
        isSubmitting = true
        errorText = nil
        // On success, AuthGateView swaps this view out for the main shell, so we
        // only need to handle the FAILURE path here — otherwise the button would
        // spin on "Creating identity…" forever (the bug live-testing surfaced
        // when the Keychain was unavailable).
        Task { @MainActor in
            let ok = await authService.registerLocalIdentity(displayName: trimmed)
            if !ok {
                isSubmitting = false
                errorText = "Couldn't create your identity on this device. Please try again."
            }
        }
    }
}

// MARK: - Feature Row (shared — also used by FindFriendsView)
struct FeatureRow: View {
    let icon: String
    let title: String

    var body: some View {
        HStack(spacing: 12) {
            Image(systemName: icon)
                .font(.title3)
                .foregroundStyle(.blue)
                .frame(width: 30)

            Text(title)
                .font(.subheadline)
                .foregroundStyle(.secondary)

            Spacer()
        }
    }
}

#Preview {
    AuthGateView()
}
